config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root   'sales_hours#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post   'foods/sort' => 'foods#sort'
  post   'foods/upload' => 'foods#upload'
  post   'waste_counts/new' => 'waste_counts#new'
  get    'foods/today_counts' => 'foods#today'
  get    'foods/search' => 'foods#search'
  get    'foods/my_today' => 'foods#my_today'
  post   'sales_hours/upload' => 'sales_hours#upload'
  resources :users
  resources :foods
  resources :waste_counts
  resources :surveys
  resources :restaurants, only: [:index, :edit, :show, :update]
  get    'current_manager' => 'application#current_manager'
  resources :sales_hours
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :waste_counts, :dependent => :destroy
  validates :price,
            :numericality => {
              :greater_than => 0,
              :less_than_or_equal_to => 1000
             }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def new
    if logged_in?
      @food = Food.new 
    else
      flash[:danger] = "Please login first."
      redirect_to login_url 
    end
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    @food.sort_order = 0
    if @food.save
      redirect_to foods_url 
    else
      render 'new'
    end
  end

  def update
    @food = Food.find(params[:id])
    respond_to do |format|
      if @food.update_attributes(food_params)
        format.html { 
          if request.xhr?
             render :text => params[:food].values.first
          else
             redirect_to foods_url, notice: 'Food item Successfully updated.' 
          end
        }
      end
    end
  end

  def edit
    @food = Food.find(params[:id])
  end

  def destroy
    Food.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to foods_url, 
                    notice: "Food successfullly removed." }
    end
  end

  def show
    @food = Food.find(params[:id])
  end

  def index
    if current_user.admin?
      store_number = params[:store] || current_user.store_number
    else
      store_number = current_user.store_number 
    end
    
    @foods = Food.all
   
    if params[:created_date].nil?
      @selected_counts = WasteCount
        .where(created_at: (Time.parse("04:00"))..(Time.now.end_of_day + 3.hours), store: store_number)
      @date = Time.now
    else
      @date = Time.parse(params[:created_date].to_s) 
      @selected_counts = WasteCount
        .where(created_at: (@date.beginning_of_day + 4.hours)..(@date.end_of_day + 3.hours), store: store_number)
    end
    @week_counts = WasteCount
      .where(created_at: (Time.now - 7.days)..Time.now, store: store_number)
    @breakfast_completed = @foods
      .where(["food_type = ?", "Breakfast Completed"])
      .order("sort_order")
    @breakfast_raw = @foods
      .where(["food_type = ?", "Breakfast Raw"])
      .order("sort_order")
    @lunch_raw = @foods
      .where(["food_type = ?", "Lunch Raw"])
      .order("sort_order")
    @lunch_completed = @foods
      .where(["food_type = ?", "Lunch Completed"])
      .order("sort_order")
  end


  def sort
    if request.xhr?  
      @food = Food.find(params[:id])
      @food.sort_order = params[:sort_order]
      @food.save
      success = { :status => "ok", :message => "Success!" }
      render :json => success  
    end
  end

  def search
    if params[:start_date][0].blank? || params[:end_date][0].blank?
      redirect_to foods_path
      flash[:error] = "We needs both dates entered, please."
    else
      start_date = Time.parse(params[:start_date].to_s)
      end_date = Time.parse(params[:end_date].to_s)
      user_id = params[:user_id][0].to_i
      if user_id != 0 
        @results = WasteCount.where(created_at: start_date..end_date, user_id: user_id)
      else
        @results = WasteCount.where(created_at: start_date..end_date)
      end
      unless @results.blank?
        respond_to do |format|
          format.html { return @results }
          format.json { render json: @results }
        end
      else
      redirect_to foods_path
      flash[:notice] = "No counts between the selected time frame." 
      end
    end
  end

  def upload
    if logged_in?
      file = params[:file]
      options = {}
      n = SmarterCSV.process(file.tempfile, options) do |array|
        # we're passing a block in, to process each resulting hash / =row (the block takes array of hashes)
        #       # when chunking is not enabled, there is only one hash in each array
        Food.create( array.first )
      end
    redirect_to foods_path
    flash[:success] = "Successfully uploaded!"
    else
      flash[:danger] = "Please login first."
      redirect_to login_url
    end
  end

  def my_today 
    @my_today = WasteCount
      .where(created_at: (Time.now.midnight + 3.hours)..Time.now, 
             user_id: current_user.id)
      .order(food_id: :asc)
    if @my_today.blank?
      redirect_to foods_path, notice: "How about you count waste first?"
    end
  end

  private
  
  def food_params
    params.require(:food).permit(:price, :type, :name, 
                                 :food_type, :wrin, :user_id, :sort_order)
  end

end

app/views/foods/_form.html.erb
<%= form_for @food, layout: :basic do |f| %>
  <%= f.text_field :wrin %>
  <%= f.text_field :name%>
 
  <%= f.select(:food_type, [['Breakfast Raw', 'Breakfast Raw'], ['Breakfast Completed', 'Breakfast Completed'], ['Lunch Raw', 'Lunch Raw'], ['Lunch Completed', 'Lunch Completed']]) %>
  <%= f.text_field :price%>
  <%= f.submit 'Save' %>
  <% if current_user.admin? %>
     <%= link_to button 'Delete', @food, method: :delete, 
       data: {confirm: "Are you sure?"}, context: :danger, class: 'pull-right' %>
     <% end %>

<% end %>

app/views/foods/_my_today.html.erb
<div class="col-xs-6">

<table class="table">
  <thead>
    <th>Product Name</th>
    <th>Count</th>
    <th>Cost</th>
    <th>Edit</th>
  <thead>
  <tbody>
    <% @my_today.each do |mt| %> 
    <% food_item = Food.find_by_id(mt.food_id) %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= mt.count %></td>
        <td><%= money_without_cents_and_with_symbol(
                food_item.price * mt.count) %>
        </td>
        <td><%= link_to icon(:remove), mt, 
                method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<div class="col-xs-6">
</div>

app/views/foods/_table.html.erb
<div class="col-sm-6">
  <table class="table table-waste">
    <thead>
      <% if ["Breakfast Raw", "Lunch Raw"].include? table_name %>
        <th>WRIN</th>
      <% end %>
      <th width="175px"><%= table_name %></th>
      <th>Edit</th>
      <th>Count</th>
      <th>Add</th>
      <th width="60px">Total Day</th>
      <th>Total Cost</th>
    </thead>
    <tbody class="sortable">
    <% foods.each do |f| %>
      <tr class="food_item" id="<%= f.id %>" data-sort="<%= f.sort_order %>">
        <% if ["Breakfast Raw", "Lunch Raw"].include? table_name %>
          <td><%= f.wrin %></td>
        <% end %>       
        <td><%= f.name.titleize %></td>
        <td>
          <%= link_to icon(:pencil), edit_food_path(f) %>
        </td>
        <td><input class="food_item_count form-control" 
              type="tel" id="food_item_count_<%= f.id %>" 
              data-product_id="<%= f.id %>" value="0"></input></td>
        <td><a id="<%= f.id %>" href="#" class="submit_food_item_count 
              glyphicon glyphicon-plus-sign"></a></td>
        <td><p id="today_count_<%= f.id %>">0</p></td>
        <td><p id="today_cost_<%=f.id %>" class="today_cost" data-price="<%= humanized_money(f.price) %>">0</p>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/foods/index.html.erb
<div id="success-msg" class="alert alert-success">
  <p class="text-center">Saved!</p>
</div>
<div class="row">

</div>
<div class="waste-counts">
  <div class="row">
    <div class="col-sm-4 pad-row">
      <div class="text-center">
        <span class="alert h4">Today's Total: </span>
        <br>
        <span id="today_total_cost" class="alert alert-success h4">0</span>
      </div> 
    </div>
    <div class="col-sm-4">
    </div>
    <div class="col-sm-3 col-sm-1-offset pad-row">
      <div class="text-center">
 
        <div class="form-group">
          <%= form_tag(foods_path, :method => 'get') do %>
            <%= date_field :created_date, nil, value: @date.strftime("%F"), class: 'btn btn-default text-center input-date form-control' %> 
            <% if current_user.admin? %>
              <%= select_tag(:store, 
                    options_for_select([['4453', 4453],['11960', 11960],  
                                        ['11785', 11785],['18056', 18056]], 
                                         selected: params[:store] ), 
                                         class: 'form-control') %>
            <% end %>
            <%= submit_tag("Go", class: 'btn btn-default') %>
          <% end %>
        </div>
        <div class="form-group">
          <%= link_to button("My Counts Today"), foods_my_today_path%>
        </div> 
        <p class="text-muted">Last counted: <%= last_count_time %></p>
      </div>
    </div>
  </div>
  <div class="row">

  </div>
  <div class="row">
     <div class="text-center">
      <button class="submit btn btn-default" type="button">Save</button>
      <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
      <a href="#" class="btn btn-danger" id="clear_counts">Clear Counts</a>
      <% if current_user.admin? %> 
        <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <%= link_to button("New Food"), new_food_path %>
      <% end %>
      <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
      <%= button(icon(:sort), id: 'turn_sort_on') %>
    </div>
  </div>
  <div class="row">
    <%= render 'foods/table', foods: @breakfast_raw, table_name: "Breakfast Raw" %>
    <%= render 'foods/table', foods: @breakfast_completed, table_name: "Breakfast Completed" %>
  <div class="row">
    <div class="text-center">
      <button class="submit btn btn-default" type="button">Save</button>
      <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
      <a href="#" class="btn btn-danger" id="clear_counts">Clear Counts</a>
      <% if current_user.admin? %> 
        <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <%= link_to button("New Food"), new_food_path %>
      <% end %>
    </div>
  </div>

  </div>
  <div class="row">
    <%= render 'foods/table', foods: @lunch_raw, table_name: "Lunch Raw" %>
    <%= render 'foods/table', foods: @lunch_completed, table_name: "Lunch Completed" %>
  </div>
  <div class="row">
    <div class="text-center">
      <button class="submit btn btn-default" type="button">Save</button>
      <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
      <a href="#" class="btn btn-danger" id="clear_counts">Clear Counts</a>
      <% if current_user.admin? %> 
        <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <%= link_to button("New Food"), new_food_path %>
      <% end %>
    </div>
  </div>
  <div class="row separator">
  </div>
  <div class="row">
    <div class="col-sm-4">
      <h3 class="text-center">Weekly Leaderboard</h3>
      <table id="week_counts" class="table">
        <thead> <th>Name</th> <th>Total Cost/Week</th> </thead> <tbody id="week_counts_body"> </tbody>
      </table>
    </div>
    <div class="col-sm-4">
      <h3 class="text-center">Yesterday's Top Waste</h3>
      <table id="top_yesterday_waste" class="table">
        <thead>
          <th>Food Item</th>
          <th>Total Cost</th>
        </thead>
        <tbody id="top_yesterday_waste_body">
        </tbody>
      </table>
    </div>
    <div class="col-sm-4">
      <h3>Search</h3>
      <%= form_tag(foods_search_path, :method => "get", id: "search-form", class: "form form-group") do %>
        <%= label_tag 'start_date', 'Start Date' %>
        <%= date_field :start_date, nil, :minute_step => 15, class: 'form-control' %>
        <%= label 'end_date', 'End Date' %>
        <%= date_field :end_date, nil, :minute_step => 15, class: 'form-control' %>
        <%= label 'user_id', 'User' %>
        <%= collection_select(:user_id, nil, User.all, :id, :fname, {include_blank: "Any User"}, {class: 'form-control'}) %>
        <%= submit_tag "Search", class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>
<script>
function getTodayCounts() {
  <% @selected_counts.each do |c|  %> 
    var curr_selector = $('#today_count_' + '<%= c.food_id %>');
    curr_selector.html('0');
  <% end %> 
  <% @selected_counts.each do |c|  %> 
    var costSelector = $('#today_cost_' + '<%= c.food_id %>');
    var currCost = parseFloat( costSelector.attr('data-price') );
    var count = 0;
    var currSelector = $('#today_count_' + '<%= c.food_id %>');
    count = parseInt( currSelector.html() );
    count += parseInt( <%= c.count %> );
    currSelector.html(count);
    costSelector.html( formatCurrency(count * currCost, 2) );
  <% end %> 
  }
getTodayCounts();

function getWeekCounts(){
  $('#week_counts_body').html("");
  <% 
    weekly_user_dollars = weekly_dollars_by_user
    weekly_user_dollars.each do |hash| 
      id = hash.keys.join
      dollars = hash.values.join
      user = User.find_by_id(id)
  %>
    $('#week_counts_body').append('<tr><td><%= user.fname %></td><td class="weekly_dollars" width="100"><%= humanized_money_with_symbol(dollars) %></td></tr>');
  $('.weekly_dollars').each( function(){
    if( <%= dollars %> > 50 ){
      $(this).addClass('danger')
    }
  });
  <% end %>
}
getWeekCounts();

function getYesterdayTopCounts(){
  $('#top_yesterday_waste_body').html("");
  <% 
    yesterday_top_waste = yesterday_top_waste_dollars
    yesterday_top_waste.each do |hash| 
      id = hash.keys.join
      dollars = hash.values.join
      food = Food.find_by_id(id)
  %>
    $('#top_yesterday_waste_body').append('<tr><td><%= food.name.titleize %></td><td class="yesterday_top_waste" width="100"><%= humanized_money_with_symbol(dollars) %></td></tr>');
  $('.weekly_dollars').each( function(){
    if( <%= dollars %> > 50 ){
      $(this).addClass('danger')
    }
  });
  <% end %>
}
getYesterdayTopCounts();
</script>

app/views/foods/my_today.html.erb
<div class="col-xs-6">

<table class="table">
  <thead>
    <th>Product Name</th>
    <th>Count</th>
    <th>Cost</th>
    <th>Time Entered</th>
    <th>Edit</th>
  <thead>
  <tbody>
    <% @my_today.each do |mt| %> 
    <% food_item = Food.find_by_id(mt.food_id) %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= mt.count %></td>
        <td><%= humanized_money_with_symbol(
                food_item.price * mt.count) %>
        </td>
        <td><%= mt.created_at.localtime.strftime("%H:%M") %></td>
        <td><%= link_to icon(:remove), mt, 
                method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<div class="col-xs-6">
</div>

app/views/foods/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <%= render 'form' %> 
    </div>
    <div class="col-sm-4">
    <%= form_tag foods_upload_path, multipart: true do %>
      <%= file_field_tag :file, class: 'btn btn-default btn-file' %>
      <%= submit_tag 'Upload CSV', class: 'btn btn-default' %>
    <% end %>
    </div>
  </div>
</div>

app/views/foods/search.html.erb
<%
  total_waste_counts = [] 
  unique_food_ids = @results.uniq.pluck(:food_id)
  unique_food_ids.each do |u|
    count = @results.where(food_id: u).sum('count')
    cost_per_item = Food.find_by_id(u).price
    total_waste_counts << { food_id: u, total_cost: count * cost_per_item, total_count: count }
  end
  total_waste_counts.sort_by! { |k| k[:total_cost]}
  total_waste_counts.reverse!
%>
<div class="col-xs-2"></div>
<div class="col-xs-8">
  <table class="table">
    <thead>
      <th>Product</th>
      <th>Total Count</th>
      <th>Total Cost<th> 
    </thead>
    <tbody>
      <% total_waste_counts.each do |wc| %>
        <tr>
          <td><%= Food.find_by_id(wc[:food_id]).name.titleize %></td>
          <td><%= wc[:total_count] %></td>
          <td><%= humanized_money_with_symbol(wc[:total_cost]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="col-xs-2"></div>

app/views/foods/show.html.erb
<table class="table">
  <tr>
    <th>WRIN</th>
    <th>Name</th>
    <th>Price</th>
    <th>Type:</th>
    <th>Created by:</th>
  </tr>
      <tr>
        <td><%= @food.wrin %></td>
        <td><%= @food.name %></td>
        <td><%= humanized_money_with_symbol(@food.price) %></td>
        <td><%= @food.food_type.titlecase %></td>
        <td><%= @food.user.fname %></td>
      </tr>
</table>