config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root   'sales_hours#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post   'foods/sort' => 'foods#sort'
  post   'foods/upload' => 'foods#upload'
  post   'waste_counts/new' => 'waste_counts#new'
  get    'foods/today_counts' => 'foods#today'
  get    'foods/search' => 'foods#search'
  get    'foods/my_today' => 'foods#my_today'
  post   'sales_hours/upload' => 'sales_hours#upload'
  resources :users
  resources :foods
  resources :waste_counts
  resources :surveys
  resources :restaurants, only: [:index, :edit, :show, :update]
  get    'current_manager' => 'application#current_manager'
  resources :sales_hours
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_one :gm, class_name: 'User', foreign_key: 'gm'
  has_many :users
  has_many :responses
  has_many :waste_counts
  has_many :surveys

  validates :store, uniqueness: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :admin_only 
  
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant updated.'  
    end
  end

  private
  
  def restaurant_params
    params.require(:restaurant).permit(:store, :name, :gm)
  end

  def admin_only
    redirect_to root_url, notice: "Sorry, must be an admin" unless is_admin?(current_user)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/index.html.erb
<table class="table">
  <thead>
    <th>National Number</th>
    <th>Name</th>
    <th>GM</th>
    <th>Total Employees</th>
    <th></th>
  </thead>
  <tbody>
    <% @restaurants.each do |r| %>  
      <tr>
        <td><%= link_to r.store, restaurant_path(r.id) %></td>
        <td><%= r.name %></td>
        <td><%= r.gm.try(:fname) || "Not Set" %></td>
        <td><%= r.users.try(:count) %></td>
        <td><%= link_to icon(:pencil), edit_restaurant_path(r.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>