config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root   'sales_hours#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post   'foods/sort' => 'foods#sort'
  post   'foods/upload' => 'foods#upload'
  post   'waste_counts/new' => 'waste_counts#new'
  get    'foods/today_counts' => 'foods#today'
  get    'foods/search' => 'foods#search'
  get    'foods/my_today' => 'foods#my_today'
  post   'sales_hours/upload' => 'sales_hours#upload'
  resources :users
  resources :foods
  resources :waste_counts
  resources :surveys
  resources :restaurants, only: [:index, :edit, :show, :update]
  get    'current_manager' => 'application#current_manager'
  resources :sales_hours
end

app/views/layouts/_nav.html.erb
<%= navbar position: :top do %>
  <%= vertical do %>
    <%= link_to 'HighGear', root_path %>
  <% end %>
  <%= horizontal do %> 
    <%= nav class: 'navbar-right' do %> 
      <% if logged_in? %>
        <%= link_to 'Sales', sales_hours_path %>
        <%= link_to 'Waste', foods_path %>
        <%= link_to current_user.fname, user_path(current_user.id),
              class: 'current_user', id: current_user.id %> 
        <% if current_user.admin? %>
          <%= link_to 'Users', users_path %>
          <%= link_to 'Surveys', surveys_path %>
        <% end %> 
        <%= link_to "Log out", logout_path, method: "delete" %>
      <% else %>
        <%= link_to "Log in", login_path %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>HighGear</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/nav" %>
<div class="container">  
  <%= render "shared/flash_messages" %>
  <%= yield %>
</div>
</body>
</html>